config/routes.rb
Rails.application.routes.draw do
  root 'page#index'

  get 'crossword/:source/:series/:identifier/:room', to: 'rooms#show', as: 'room'
  get 'crossword/:source/:series/:identifier', to: 'crosswords#show', as: 'crossword'
end

app/models/crossword.rb
class Crossword

  def initialize(crossword_data)
    @title = crossword_data.fetch('title')
    @source = crossword_data.fetch('source')
    @series = crossword_data.fetch('series')
    @identifier = crossword_data.fetch('identifier')
    @date = crossword_data.fetch('date')
  end

  attr_reader :title, :source, :series, :identifier

  def date
    (Time.xmlschema(@date).utc + 2.hours).to_date
  end

  def name
    formatted_time = date.strftime("%A %-d %b")
    if title.include?(' No ')
      number = title.split(' No ').last
      "#{formatted_time} (No #{number})"
    else
      "#{formatted_time}"
    end
  end

  def ==(other)
    other && other.instance_of?(Crossword) && other.identifier == self.identifier
  end

  def to_json
    {
      title: @title,
      source: @source,
      series: @series,
      identifier: @identifier,
      date: @date
    }.to_json
  end

  def save
    key = "crossword-series-#{self.series}"
    crosswords = JSON.parse(redis.get(key) || '[]').map{|crossword_data| Crossword.new(crossword_data)}
    if crosswords.none? { |existing_crossword| existing_crossword == self }
      crosswords.unshift(self)
      redis.set(key, crosswords.take(5).to_json)
    end
  end

  def redis
    @redis ||= Redis.new
  end

end

app/models/crossword_feed.rb
class CrosswordFeed
  def self.load
    response = Faraday.get "https://www.theguardian.com/crosswords/rss"
    xml = Nokogiri::XML(response.body)
    xml.css('item').each do |element|
      link = element.css('link').text
      series, identifier = link.split('/').last(2)
      next unless series.in?(Series::SERIES)

      crossword = Crossword.new(
        "title" => element.css('title').text,
        "source" => 'guardian',
        "series" => series,
        "identifier" => identifier,
        "date" => element.at('dc|date').text
      )
      crossword.save
    end
  end

  def self.redis
    @redis ||= Redis.new
  end

end

app/models/series.rb
class Series
  SERIES = ['quiptic', 'quick', 'weekend', 'cryptic', 'speedy', 'prize', 'everyman']

  def self.get_all
    keys = SERIES.map{|name| "crossword-series-#{name}"}
    series = redis.mget(*keys).map{|a_series| JSON.parse(a_series || '[]') }
    SERIES.zip(series).map do |name, crossword_datas|
      [name, crossword_datas.map {|crossword_data| Crossword.new(crossword_data)}]
    end.select{|name, series| series.any? }
  end


  def self.redis
    @redis ||= Redis.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/crosswords_controller.rb
class CrosswordsController < ApplicationController
  def show
    redirect_to room_path(
      source: params[:source],
      series: params[:series],
      identifier: params[:identifier],
      room: SecureRandom.uuid
    )
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    @series_with_crosswords = Series.get_all
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    raise ActionController::RoutingError.new('Source not Found') unless params[:source] == 'guardian'
    raise ActionController::RoutingError.new('Series not Found') unless params[:series].in?(Series::SERIES)
    @crossword = crossword
    @parsed_crossword = JSON.parse(crossword)
    @url = url
  end

  def crossword_identifier
    [params[:source], params[:series], params[:identifier]].join('/')
  end
  helper_method :crossword_identifier

  def crossword
    if redis.exists(crossword_identifier)
      redis.get(crossword_identifier)
    else
      get_crossword_data.tap {|data| redis.set(crossword_identifier, data) }
    end
  end

  def get_crossword_data
    response = Faraday.get(url)
    html = Nokogiri::HTML(response.body)
    crossword_element = html.css('.js-crossword')
    raise ActionController::RoutingError.new('Element not Found') unless crossword_element.any?
    crossword_element.first['data-crossword-data']
  end

  def url
    "https://www.theguardian.com/crosswords/#{params[:series]}/#{params[:identifier]}"
  end

  def redis
    @redis ||= Redis.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Several People are Solving</title>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:800" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "application" %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-18262427-4"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-18262427-4');
    </script>
  </head>
  <body>
    <div class="banner">
      <a href="/"><h2>Several People are Solving</h2></a>
    </div>
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/page/index.html.erb
<p class="intro">
  Pick one of the crosswords below then share the link with friends to solve together.
</p>

<%- @series_with_crosswords.each do |series, crosswords| -%>
  <h3><%= series.titleize %></h3>
  <ul>
  <%- crosswords.each do |crossword| -%>
    <li>
      <%= link_to(crossword.name, crossword_path(crossword.source, crossword.series, crossword.identifier)) %>
    </li>
  <%- end -%>
  </ul>
<%- end -%>

<p class="about">
  <strong>Several People are Solving</strong> is an experiment with multiplayer crosswords created by <a href="https://chriszetter.com">Chris Zetter</a>. You can <a href="https://github.com/zetter/multicrosser">view the code on GitHub</a>.
</p>

app/views/rooms/show.html.erb
<h1><%= @parsed_crossword['name'] %></h1>
<p>
  <%= Time.at(@parsed_crossword['date']/1000).to_date.strftime("%A %-d %B") %> -
  <%- if @parsed_crossword['creator'] -%>
    Set by <%= @parsed_crossword['creator']['name'] %>
    -
  <%- end -%>
  <a href="<%= @url %>">Published by the Guardian</a>
</p>

<%= content_tag(:div, '', class: 'js-crossword', data: {
  crossword: @crossword,
  'crossword-identifier': crossword_identifier,
  room: params[:room],
}) %>

<%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

<p>Share this page with others to solve this crossword with them.</p>